### ISSUE TITLE
[request] custom background

### ISSUE THREAD

**Issue by wrozwad** [RiccardoMoro/RMSwitch#3]
It will be great to have a possibility to add custom background to the switch. Or have material switch background with possibility to add drawable to left and right.

**Comment by RiccardoMoro** [comment]
I'm on it, in the next release I'll add this features.
(Not too soon, i've been busy with work lately)

**Comment by RiccardoMoro** [comment]
@sosite Added the "android" design which (almost) looks like the default android switch, and now you can set drawable objects or drawable resources as toggle images.

**Comment by wrozwad** [comment]
Thx!
