### ISSUE TITLE
strange loop if in relative layout

### ISSUE THREAD

**Issue by ksatalsin** [RiccardoMoro/RMSwitch#7]
....android E/RMSwitch: Paddings
....android E/RMSwitch: Margins
....android E/RMSwitch: Paddings
....android E/RMSwitch: Margins
....android E/RMSwitch: Paddings
....android E/RMSwitch: Margins
....android E/RMSwitch: Paddings
....android E/RMSwitch: Margins
....android E/RMSwitch: Paddings
....android E/RMSwitch: Margins

**Comment by RiccardoMoro** [comment]
It's just logs or the view is actually hanging the UI with a loop? (BTW thanks, you made me notice that I forgot those two logs inside the Library.. my bad)
Because in the sample itself I'm using the switches inside a RelativeLayout and they are not freezing the UI

**Comment by RiccardoMoro** [comment]
@ksatalsin I've removed the logs, as soon as you confirm that the UI do not freeze, I'll push the new version (1.2.2)
Thanks

**Comment by RiccardoMoro** [comment]
I'll push and close this issue.. reopen it if you were having UI-freeze problems
